x <- scan("results.txt", list(0,0,0))
pdf("ratio.pdf")
plot(x[[1]], x[[2]]/(x[[2]]+x[[3]]), type='l', main="Success vs. Time", xlab="Seconds in Epoch", ylab="Success Ratio")
dev.off()
pdf("success.pdf")
plot(x[[1]], x[[2]], type='l', main="Successes vs. Time", xlab="Seconds in Epoch", ylab="Number of Tests Passed")
dev.off()
pdf("coverage.pdf")
plot(x[[1]], x[[2]] + x[[3]], type='l', main="Coverage vs. Time", xlab="Seconds in Epoch", ylab="Total Number of Tests")
dev.off()
