#ifndef _MOUSETOOL_DEF_
#define _MOUSETOOL_DEF_
                           
#define IDC_LBUTTON_ONDAM		2300
#define IDC_LBUTTON_ONRELEASE		2310
#define IDC_LBUTTON_ONREACH		2320
#define IDC_LBUTTON_ONHEADWATER	2330
#define IDC_MBUTTON_ONDAM		2340
#define IDC_MBUTTON_ONRELEASE		2350
#define IDC_MBUTTON_ONREACH		2360
#define IDC_MBUTTON_ONHEADWATER	2365
#define IDC_RBUTTON_ONDAM		2366
#define IDC_RBUTTON_ONRELEASE		2367
#define IDC_RBUTTON_ONREACH		2368
#define IDC_RBUTTON_ONHEADWATER	2369

#endif

